apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  labels:
    env: prod
    owner: desausag
spec:
  selector:
    project: ftps
  ports:
    - protocol: TCP
      port: 21
      targetPort: 21
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    project: ftps #его лейбл
spec: #С какими подами будет работать с проджект кгб
  replicas: 1
  selector:
    matchLabels:
      project: ftps
  template:
    metadata:
      labels:
        project: ftps
    spec:
      containers:
        - name: ftps
          image: ftps
          imagePullPolicy: Never
          ports:
            - containerPort: 21