apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: main-claster
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      protocol: TCP
  selector:
    app: php-lbl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-lbl
  template:
    metadata:
      labels:
        app: php-lbl
    spec:
      containers:
        - image: phpmyadmin
          imagePullPolicy: Never
          name: phpmyadmin
          ports:
            - containerPort: 5000
